### ISSUE TITLE
Quick-Start

### ISSUE THREAD

**Issue by cschaf** [Necrobot-Private/PokemonGo.RocketAPI#164]
Hi guys,

could you give me a quick-start help, how to setup the project and login with a trainer account?

Greetings
cschaf

Sorry, for the issue. I didnt find how to contact you via github or email.

**Comment by Furtif** [comment]
Do you want to use Feroxrev based api? Is that what you want?

**Comment by cschaf** [comment]
Yes the PokemonGo.RocketAPI

**Comment by Furtif** [comment]
see how logic makes the calls, client, etc ... https://github.com/Necrobot-Private/PoGo.NecroBot.Logic

**Comment by cschaf** [comment]
Thank you very much! If I have further question can I mail you?

**Comment by Furtif** [comment]
use discord https://discord.gg/7FWyWVp if you want

**Comment by Furtif** [comment]
Updated readme file [here](https://github.com/TheUnnamedOrganisation/FeroxRev/blob/master/README.md)

**Comment by Furtif** [comment]
note uses .configureawait(false);  👍
