### ISSUE TITLE
Swap pokemon is not working

### ISSUE THREAD

**Issue by ziomber** [Necrobot-Private/PokemonGo.RocketAPI#45]
Result of call
{ "type": "ACTION_SWAP_POKEMON", "actionStartMs": "1486065737505", "durationMs": 1000, "targetIndex": -1, "activePokemonId": "**195007357855868549**" } result: { "result": "**SUCCESS**", "battleLog": ...many trashes here..., { "type": "ACTION_SWAP_POKEMON", "actionStartMs": "1486065737505", "durationMs": 1000, "targetIndex": -1, "activePokemonId": "195007357855868549" },..., "battleId": "0a30fd84a35a4e748055753ca13f38b1.16_3826149097041938497_1450918003172983882_1486065687990", "activeDefender": { "pokemonData": { "id": "1450918003172983882", "pokemonId": "CHARIZARD", "cp": 2191, "stamina": 240, "staminaMax": 240, "move1": "EMBER_FAST", "move2": "FLAMETHROWER", "ownerName": "TheSexyMaryse", "heightM": 1.33428073, "weightKg": 38.2948875, "individualAttack": 14, "individualDefense": 14, "individualStamina": 12, "cpMultiplier": 0.7193991, "pokeball": "ITEM_ULTRA_BALL", "creationTimeMs": "1482955131540", "favorite": 1, "pokemonDisplay": { "gender": "MALE" } }, "currentHealth": 88, "currentEnergy": 46 }, "activeAttacker": { "pokemonData": { "id": "**6264199969138303188**", "pokemonId": "DRAGONITE", "cp": 2240, "stamina": 123, "staminaMax": 123, "move1": "STEEL_WING_FAST", "move2": "HYPER_BEAM", "heightM": 2.259089, "weightKg": 222.059448, "individualAttack": 15, "individualDefense": 13, "individualStamina": 15, "cpMultiplier": 0.6265671, "pokeball": "ITEM_ULTRA_BALL", "battlesAttacked": 44, "creationTimeMs": "1485730710897", "pokemonDisplay": { "gender": "FEMALE" } }, "currentHealth": 123 } }

**Comment by jjskuld** [comment]
Recent gym changes make this bug no longer applicable, so closing this for now.
