### ISSUE TITLE
GetStoreItemsRequest

### ISSUE THREAD

**Issue by DiviNeMint** [Necrobot-Private/PokemonGo.RocketAPI#47]
Does anyone know how to get shop items ?
I tried again and again,but all response were errors.
Now, I don't have any idea to let it work,but I have some question about it.
Do we lost the "GetStoreItemsRequest" file ?
Or... I forget something? if so, what should i post when i want to get store items?

**Comment by samuraitruong** [comment]
that is GetInventoryRequest

**Comment by DiviNeMint** [comment]
Really...?
I want to get shop's item instead of player's Inventory.
So... GetInventoryRequest is including that?
But I can't find anything about shop's info.
Can you help me?

**Comment by samuraitruong** [comment]
ooh, sorry for miss understool, Why you need getshopitem? for auto buy item?

________________________________

**Comment by DiviNeMint** [comment]
yes, I want to upgrade storage.
