### ISSUE TITLE
Buy Item With PokeCoins

### ISSUE THREAD

**Issue by DiviNeMint** [Necrobot-Private/PokemonGo.RocketAPI#53]
I find the ItemId of goods, but I have a new trouble...
The BuyItemRequest (and Response) are Platform's Datas
So i add that to RequestEnvelops.PlatformRequests( like UnknownPtr8 do ), but all responses i get are empty. ( I try to add the PlatformRequests within GetPlayer, GetMapObject ...... etc. )
Does anyone have any idea with this ?
If i succeed, I will share the code.

**Comment by jjskuld** [comment]
I don't think there is an API exposed for this.
