### ISSUE TITLE
Many hash collisions in inventory items

### ISSUE THREAD

**Issue by jessdecker** [Necrobot-Private/PokemonGo.RocketAPI#57]
The auto-generated code in the POGOProtos protobuf objects for GetHashCode() isn't generating unique hash codes for pokedex entries or pokemon family entries. This causes collisions in the InventoryItems dictionary of \Rpc\Inventory.cs. The side effects here are all over the place and can seem not-reproducible. Debug through this on the initial player data load and you should see it happening pretty easily with a large enough inventory.
        
```
private void AddInventoryItem(InventoryItem item)
        {
            var hash = item.GetHashCode();
            InventoryItem x;            
            if (InventoryItems.TryGetValue(hash, out x))
            {
                // look at x.GetHashCode() and item.HashCode(). Can be very diff objs, 
                // but hash codes are the same.
                Debugger.Break(); 
            }
            InventoryItems[hash] = item;
        }
```

**Comment by jjskuld** [comment]
Thanks for figuring this out. I'll work around this issue tonight. We should generate our own custom key for the hash instead of relying on the hash code.

**Comment by jjskuld** [comment]
Please retest with latest code. It should hopefully be fixed now

**Comment by jessdecker** [comment]
Yep! All good.
